[package]
authors = ["Wim Looman <wim@nemo157.com>"]
name = "ripfs"
version = "0.1.0"

[dependencies]
futures = "*"
maddr = "0.2.0"
mhash = "0.2.0"
tokio-core = "*"
tokio-io = "0.1.2"

[dependencies.libp2p]
path = "../libp2p-rs"

[dependencies.msgio]
path = "../msgio-rs"
